export const availableFonts_Classic = [
    { name: "Arvo", id: 1, class: "font-arvo" },
    { name: "Bitter", id: 2, class: "font-bitter" },
    { name: "Bungee Spice", id: 3, class: "font-bungee-spice" },
    { name: "Calistoga", id: 4, class: "font-calistoga" },
    { name: "Crimson Text", id: 5, class: "font-crimson-text" },
    { name: "Dancing Script", id: 6, class: "font-dancing-script" },
    { name: "EB Garamond", id: 7, class: "font-eb-garamond" },
    { name: "Handjet", id: 8, class: "font-handjet" },
    { name: "IBM Plex Serif", id: 9, class: "font-ibm-plex-serif" },
    { name: "Libre Baskerville", id: 10, class: "font-libre-baskerville" },
    { name: "Lora", id: 11, class: "font-lora" },
    { name: "Noto Sans JP", id: 12, class: "font-noto-sans-jp" },
    { name: "Noto Sans SC", id: 13, class: "font-noto-sans-sc" },
];
