export const SupportGroups = [
    {
        type: 0,
        caption:'Support Creator',
        cardTitle: "Explore more of my Projects.",
        cardMessage: "Take a look at my projects and the things I've added to GitHub. You'll find a mix of different stuff I've worked on, and I'm excited to share them with you!",
        title: "Discover My GitHub Projects",
        message: "I invite you to explore my GitHub profile, where you can find an array of exciting projects and contributions. Feel free to take a look, and if you find something you like, don't hesitate to show your support by leaving a star ⭐",
        linkTo: "https://github.com/fabiconcept",
    },
    {
        type: 1,
        caption:'#StandWithUkraine',
        cardTitle: "War is never the answer.",
        cardMessage: "Display a support banner to encourage your visitors to #StandWithUkraine, donate and discover resources, and support the right for people everywhere to live in peace.",
        title: "War is not the answer.",
        message: "I'm driving awareness, donations and support to #StandWithUkraine, and the right for people everywhere to live in peace. Will you join me?",
        linkTo: "https://linktr.ee/withukraine",
    },
    {
        type: 2,
        caption:'Anti-Racism',
        cardTitle: "Racism is an international emergency.",
        cardMessage: "Display a support banner on your Linktree allowing your visitors to donate and discover resources in support of anti-racism, justice and equality.",
        title: "Support Anti-Racism",
        message: "I'm raising awareness, driving donations and sharing information in support of racial justice and equality. Will you join me?",
        linkTo: "https://linktr.ee/ACTION",
    },
    {
        type: 3,
        caption:'Pride',
        cardTitle: "Support the LGBTQIA+ community",
        cardMessage: "Display a support banner to raise awareness and funds for the LGBTQIA+ community during Pride month.",
        title: "Protect LGBTQIA+ rights",
        message: "In celebration of Pride, I'm raising awareness and funds to support the LGBTQIA+ community. Join me.",
        linkTo: "https://linktr.ee/PrideMonth",
    },
]